name: CD Jekyll Site

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y lftp git gettext-base
          gem install bundler
          bundle install

      - name: Build site
        run: ./utils/build-site.sh

      - name: Deploy site
        env:
          SFTP_HOST: ${{ vars.SFTP_HOST }}
          SFTP_USER: ${{ vars.SFTP_USER }}
          SFTP_KEY_VALUE: ${{ secrets.SFTP_KEY_VALUE }}
          SFTP_TARGET_DIR: ${{ vars.SFTP_TARGET_DIR }}
          CONTACT_FORM_SMTP_USERNAME: ${{ vars.CONTACT_FORM_SMTP_USERNAME }}
          CONTACT_FORM_SMTP_PASSWORD: ${{ vars.CONTACT_FORM_SMTP_PASSWORD }}
          CONTACT_FORM_TO_EMAIL: ${{ vars.CONTACT_FORM_TO_EMAIL }}
        run: ./utils/deploy-site.sh